on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
name: CD of the ontology
jobs:

  validate-ontology:
    uses: ./.github/workflows/validate.yml

  deploy-ontology:
    uses: ./.github/workflows/deploy.yml
    needs: validate-ontology
    with:
      POKEMONKG_ORG_FTP_URL: ${{ vars.POKEMONKG_ORG_FTP_URL }}
      POKEMONKG_ORG_FTP_PORT: ${{ vars.POKEMONKG_ORG_FTP_PORT }}
    secrets:
      POKEMONKG_ORG_FTP_USERNAME: ${{ secrets.POKEMONKG_ORG_FTP_USERNAME }}
      POKEMONKG_ORG_FTP_PASSWORD: ${{ secrets.POKEMONKG_ORG_FTP_PASSWORD }}