on: push
name: Deploy ontology and documentation
jobs:

  deploy:
    name: Deploy ontology and documentation
    environment: pokemonkg-org
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'
      JENA_VERSION: '4.10.0'
      WIDOCO_VERSION: '1.4.20'
    steps:
    - name: Setup Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: ${{ vars.JAVA_VERSION }}

    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.POKEMONKG_ORG_FTP_URL }}
        username: ${{ secrets.POKEMONKG_ORG_FTP_USERNAME }}
        password: ${{ secrets.POKEMONKG_ORG_FTP_PASSWORD }}
        protocol: 'ftps'
        port: ${{ vars.POKEMONKG_ORG_FTP_PORT }}
        local-dir: './'
        server-dir: 'public_html/test/'
