on: push
name: Deploy ontology and documentation
jobs:

  deploy:
    name: Deploy ontology and documentation
    environment: pokemonkg-org
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'
      JENA_VERSION: '4.10.0'
      WIDOCO_VERSION: '1.4.20'
    steps:
    - name: Setup Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-package: 'jre'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup Jena CLI apps
      run: |
        wget https://dlcdn.apache.org/jena/binaries/apache-jena-${JENA_VERSION}.tar.gz
        tar -xzf apache-jena-${JENA_VERSION}.tar.gz
        rm -f apache-jena-${JENA_VERSION}.tar.gz
        mv apache-jena-${JENA_VERSION} /opt/jena

    - name: Setup Widoco
      run: |
        wget https://github.com/dgarijo/Widoco/releases/download/v${WIDOCO_VERSION}/widoco-${WIDOCO_VERSION}-jar-with-dependencies_JDK-${JAVA_VERSION}.jar
        mv widoco-${WIDOCO_VERSION}-jar-with-dependencies_JDK-${JAVA_VERSION}.jar /opt/widoco/run.jar
    
    - name: Create documentation
      run: |
        java -jar /opt/widoco/run.jar -confFile config.properties -ontFile pokemon.ttl -outFolder out -lang "en" -webVowl -rewriteAll

    - name: Get latest code
      uses: actions/checkout@v3

    - name: Serialize ontology into different formats
      run: |
        mkdir -p out/
        /opt/jena/bin/riot --syntax=Turtle --nobase --check --strict --formatted=Turtle pokemon.ttl > out/ontology.ttl
        /opt/jena/bin/riot --syntax=Turtle --nobase --check --strict --formatted=N-Triples pokemon.ttl > out/ontology.nt
        /opt/jena/bin/riot --syntax=Turtle --nobase --check --strict --formatted=RDFXML pokemon.ttl > out/ontology.xml
        /opt/jena/bin/riot --syntax=Turtle --nobase --check --strict --formatted=JSON-LD pokemon.ttl > out/ontology.json

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.POKEMONKG_ORG_FTP_URL }}
        username: ${{ secrets.POKEMONKG_ORG_FTP_USERNAME }}
        password: ${{ secrets.POKEMONKG_ORG_FTP_PASSWORD }}
        protocol: 'ftps'
        port: ${{ vars.POKEMONKG_ORG_FTP_PORT }}
        local-dir: './'
        server-dir: 'public_html/test/'
